version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14
        environment:
          FLASK_CONFIG: testing
    steps:
      name: Build and push Docker image
      command:
        docker build -t todo:$TAG .      